/**
 * Hrefs the Group and Expense detail screens navigate to. Typed routes are generated by Metro and are stale until it
 * runs (and the sheets and settings belong to other stacks), so the paths are cast here, in one place.
 */
import type { Href } from 'expo-router';

const enc = encodeURIComponent;

export const groupHrefs = {
  groups: '/' as Href,
  group: (id: string): Href => `/group/${enc(id)}` as Href,
  settings: (id: string): Href => `/group/${enc(id)}/settings` as Href,
  addExpense: (id: string): Href => `/group/${enc(id)}/expense` as Href,
  editExpense: (id: string, expenseId: string): Href =>
    `/group/${enc(id)}/expense?edit=${enc(expenseId)}` as Href,
  expense: (id: string, expenseId: string): Href => `/group/${enc(id)}/${enc(expenseId)}` as Href,
  /** The Settle sheet, prefilled from a settle-list row (from → to → amount in minor units). */
  settle: (id: string, transfer?: { from: string; to: string; amount: number }): Href =>
    (transfer === undefined
      ? `/group/${enc(id)}/settle`
      : `/group/${enc(id)}/settle?from=${enc(transfer.from)}&to=${enc(transfer.to)}&amount=${transfer.amount}`) as Href,
  /** Join with the pasted invite (the closed banner's "Paste"). */
  joinWithCode: (code: string): Href => `/join?code=${enc(code)}` as Href,
};
