/**
 * The emoji picker's data: the board's "Suggested" grid (EmojiPicker board, in its order) and a catalogue with search
 * words. An avatar is exactly one emoji (core `isSingleEmoji`); typing any emoji into the search offers it too.
 */
import { isSingleEmoji } from '@even/core';

/** The EmojiPicker board's grid, row by row (7 columns). */
// prettier-ignore
export const SUGGESTED: readonly string[] = [
  '🌲', '🏔️', '🏕️', '🌊', '🌙', '☀️', '⭐',
  '🦊', '🐻', '🦉', '🐢', '🐙', '🦋', '🐝',
  '🌻', '🍄', '🌵', '🍁', '🍋', '🍓', '🥑',
  '☕', '🍕', '🍜', '🥐', '🍩', '🧁', '🍉',
  '🎸', '🎧', '📷', '🎨', '📚', '🧭', '⚽',
  '🚲', '⛵', '🛶', '🎈', '🪁', '🧩', '🎲',
];

/** emoji → search words. The suggested ones first, then more of the same kinds. */
const CATALOGUE: readonly (readonly [string, string])[] = [
  ['🌲', 'evergreen tree pine forest'],
  ['🏔️', 'snow capped mountain peak'],
  ['🏕️', 'camping tent camp'],
  ['🌊', 'water wave ocean sea surf'],
  ['🌙', 'crescent moon night'],
  ['☀️', 'sun sunny'],
  ['⭐', 'star'],
  ['🦊', 'fox'],
  ['🐻', 'bear'],
  ['🦉', 'owl bird'],
  ['🐢', 'turtle'],
  ['🐙', 'octopus'],
  ['🦋', 'butterfly'],
  ['🐝', 'bee honeybee'],
  ['🌻', 'sunflower flower'],
  ['🍄', 'mushroom'],
  ['🌵', 'cactus desert'],
  ['🍁', 'maple leaf autumn fall canada'],
  ['🍋', 'lemon fruit'],
  ['🍓', 'strawberry fruit berry'],
  ['🥑', 'avocado'],
  ['☕', 'coffee hot beverage cafe tea'],
  ['🍕', 'pizza'],
  ['🍜', 'noodles ramen soup bowl'],
  ['🥐', 'croissant bread pastry'],
  ['🍩', 'doughnut donut'],
  ['🧁', 'cupcake cake'],
  ['🍉', 'watermelon fruit'],
  ['🎸', 'guitar music'],
  ['🎧', 'headphone headphones music'],
  ['📷', 'camera photo'],
  ['🎨', 'artist palette art paint'],
  ['📚', 'books library read'],
  ['🧭', 'compass travel'],
  ['⚽', 'soccer football ball'],
  ['🚲', 'bicycle bike cycling'],
  ['⛵', 'sailboat boat sail'],
  ['🛶', 'canoe kayak paddle'],
  ['🎈', 'balloon party'],
  ['🪁', 'kite'],
  ['🧩', 'puzzle piece jigsaw'],
  ['🎲', 'game die dice'],
  ['🐶', 'dog puppy'],
  ['🐱', 'cat kitten'],
  ['🐭', 'mouse'],
  ['🐰', 'rabbit bunny'],
  ['🐼', 'panda'],
  ['🐨', 'koala'],
  ['🐯', 'tiger'],
  ['🦁', 'lion'],
  ['🐮', 'cow'],
  ['🐷', 'pig'],
  ['🐸', 'frog'],
  ['🐵', 'monkey'],
  ['🐧', 'penguin bird'],
  ['🐦', 'bird'],
  ['🦆', 'duck bird'],
  ['🦅', 'eagle bird'],
  ['🐺', 'wolf'],
  ['🦝', 'raccoon'],
  ['🦔', 'hedgehog'],
  ['🦦', 'otter'],
  ['🦥', 'sloth'],
  ['🐿️', 'chipmunk squirrel'],
  ['🦌', 'deer'],
  ['🦬', 'bison buffalo'],
  ['🐴', 'horse'],
  ['🦄', 'unicorn'],
  ['🐳', 'whale'],
  ['🐬', 'dolphin'],
  ['🦈', 'shark'],
  ['🐠', 'tropical fish'],
  ['🦀', 'crab'],
  ['🐌', 'snail'],
  ['🐞', 'lady beetle ladybug'],
  ['🦒', 'giraffe'],
  ['🐘', 'elephant'],
  ['🦩', 'flamingo bird'],
  ['🦜', 'parrot bird'],
  ['🌸', 'cherry blossom flower'],
  ['🌷', 'tulip flower'],
  ['🌹', 'rose flower'],
  ['🌼', 'blossom flower daisy'],
  ['🌿', 'herb plant leaf'],
  ['🍀', 'four leaf clover luck'],
  ['🌴', 'palm tree beach'],
  ['🌳', 'deciduous tree'],
  ['🌾', 'sheaf rice grain'],
  ['🪴', 'potted plant'],
  ['🌈', 'rainbow'],
  ['⛅', 'sun behind cloud weather'],
  ['❄️', 'snowflake snow winter cold'],
  ['⚡', 'high voltage lightning'],
  ['🔥', 'fire flame'],
  ['💧', 'droplet water'],
  ['🌋', 'volcano'],
  ['🏝️', 'desert island beach'],
  ['🏖️', 'beach umbrella'],
  ['🏜️', 'desert'],
  ['🌅', 'sunrise'],
  ['🌌', 'milky way night sky space'],
  ['🪐', 'ringed planet saturn space'],
  ['🌍', 'globe earth world europe africa'],
  ['🌎', 'globe earth world americas'],
  ['🌏', 'globe earth world asia australia'],
  ['🍎', 'red apple fruit'],
  ['🍐', 'pear fruit'],
  ['🍊', 'tangerine orange fruit'],
  ['🍌', 'banana fruit'],
  ['🍇', 'grapes fruit'],
  ['🫐', 'blueberries fruit berry'],
  ['🍒', 'cherries fruit'],
  ['🍑', 'peach fruit'],
  ['🥭', 'mango fruit'],
  ['🍍', 'pineapple fruit'],
  ['🥥', 'coconut'],
  ['🥝', 'kiwi fruit'],
  ['🍅', 'tomato'],
  ['🥕', 'carrot'],
  ['🌽', 'corn maize'],
  ['🌶️', 'hot pepper chili'],
  ['🥦', 'broccoli'],
  ['🧄', 'garlic'],
  ['🥨', 'pretzel'],
  ['🥯', 'bagel'],
  ['🍞', 'bread'],
  ['🧀', 'cheese'],
  ['🥚', 'egg'],
  ['🥞', 'pancakes breakfast'],
  ['🧇', 'waffle breakfast'],
  ['🥓', 'bacon'],
  ['🍔', 'hamburger burger'],
  ['🍟', 'french fries'],
  ['🌭', 'hot dog'],
  ['🌮', 'taco'],
  ['🌯', 'burrito'],
  ['🥗', 'green salad'],
  ['🍝', 'spaghetti pasta'],
  ['🍣', 'sushi'],
  ['🍱', 'bento box'],
  ['🥟', 'dumpling'],
  ['🍛', 'curry rice'],
  ['🍙', 'rice ball onigiri'],
  ['🍤', 'fried shrimp tempura'],
  ['🍦', 'soft ice cream'],
  ['🍪', 'cookie'],
  ['🎂', 'birthday cake'],
  ['🍰', 'shortcake cake'],
  ['🍫', 'chocolate bar'],
  ['🍿', 'popcorn movie'],
  ['🍯', 'honey pot'],
  ['🍵', 'teacup tea matcha'],
  ['🧋', 'bubble tea boba'],
  ['🥤', 'cup with straw soda drink'],
  ['🍺', 'beer mug'],
  ['🍻', 'clinking beer mugs cheers'],
  ['🍷', 'wine glass'],
  ['🥂', 'clinking glasses champagne cheers'],
  ['🍸', 'cocktail glass martini'],
  ['🍹', 'tropical drink cocktail'],
  ['🎹', 'musical keyboard piano music'],
  ['🎺', 'trumpet music'],
  ['🥁', 'drum music'],
  ['🎻', 'violin music'],
  ['🎤', 'microphone karaoke sing'],
  ['🎬', 'clapper board movie film'],
  ['🎮', 'video game controller'],
  ['🕹️', 'joystick game'],
  ['♟️', 'chess pawn'],
  ['🎯', 'direct hit target darts'],
  ['🎳', 'bowling'],
  ['🏀', 'basketball ball'],
  ['🏈', 'american football ball'],
  ['⚾', 'baseball ball'],
  ['🎾', 'tennis ball'],
  ['🏐', 'volleyball ball'],
  ['🏓', 'ping pong table tennis'],
  ['🏸', 'badminton'],
  ['🏒', 'ice hockey'],
  ['⛳', 'golf flag'],
  ['🏂', 'snowboarder snowboard'],
  ['⛷️', 'skier ski'],
  ['🏄', 'surfer surf'],
  ['🏊', 'swimmer swim'],
  ['🧗', 'climber climbing'],
  ['🚴', 'cyclist bike'],
  ['🏃', 'runner running'],
  ['🧘', 'yoga lotus'],
  ['🥾', 'hiking boot hike'],
  ['🎿', 'skis ski'],
  ['⛸️', 'ice skate'],
  ['🛹', 'skateboard'],
  ['🚗', 'car automobile'],
  ['🚙', 'suv car'],
  ['🚐', 'minibus van'],
  ['🚌', 'bus'],
  ['🚆', 'train'],
  ['🚀', 'rocket space'],
  ['✈️', 'airplane plane travel flight'],
  ['🚁', 'helicopter'],
  ['🛵', 'motor scooter'],
  ['🏍️', 'motorcycle'],
  ['🚤', 'speedboat boat'],
  ['⛺', 'tent camping'],
  ['🏠', 'house home'],
  ['🏡', 'house with garden home'],
  ['🏰', 'castle'],
  ['🗼', 'tokyo tower'],
  ['🗽', 'statue of liberty new york'],
  ['🎡', 'ferris wheel'],
  ['🎢', 'roller coaster'],
  ['🎪', 'circus tent'],
  ['🗺️', 'world map travel'],
  ['🧳', 'luggage suitcase travel'],
  ['🎒', 'backpack'],
  ['👑', 'crown king queen'],
  ['🎩', 'top hat'],
  ['🧢', 'billed cap'],
  ['👓', 'glasses'],
  ['🕶️', 'sunglasses cool'],
  ['💎', 'gem stone diamond'],
  ['🔑', 'key'],
  ['💡', 'light bulb idea'],
  ['📱', 'mobile phone'],
  ['💻', 'laptop computer'],
  ['⌚', 'watch'],
  ['📖', 'open book read'],
  ['✏️', 'pencil'],
  ['🖋️', 'fountain pen'],
  ['🧶', 'yarn knitting'],
  ['🪴', 'potted plant'],
  ['🕯️', 'candle'],
  ['🎁', 'wrapped gift present'],
  ['🎉', 'party popper celebration'],
  ['🎊', 'confetti ball'],
  ['🎃', 'jack o lantern pumpkin halloween'],
  ['🎄', 'christmas tree'],
  ['❤️', 'red heart love'],
  ['🧡', 'orange heart'],
  ['💛', 'yellow heart'],
  ['💚', 'green heart'],
  ['💙', 'blue heart'],
  ['💜', 'purple heart'],
  ['🖤', 'black heart'],
  ['🤍', 'white heart'],
  ['✨', 'sparkles'],
  ['🌟', 'glowing star'],
  ['💫', 'dizzy'],
  ['☘️', 'shamrock'],
  ['😀', 'grinning face smile happy'],
  ['😄', 'grinning face smiling eyes happy'],
  ['😊', 'smiling face blush'],
  ['😎', 'smiling face sunglasses cool'],
  ['🤓', 'nerd face'],
  ['🥳', 'partying face party'],
  ['😴', 'sleeping face'],
  ['🤠', 'cowboy hat face'],
  ['👻', 'ghost'],
  ['👽', 'alien'],
  ['🤖', 'robot'],
  ['👾', 'alien monster game'],
  ['💩', 'pile of poo'],
  ['👋', 'waving hand wave hello'],
  ['👍', 'thumbs up'],
  ['✌️', 'victory hand peace'],
  ['🙌', 'raising hands'],
];

/** Emoji for a search: any word starting with each typed word; an emoji typed into the search is offered itself. */
export function searchEmoji(query: string): string[] {
  const q = query.trim().toLowerCase();
  if (q === '') return [...SUGGESTED];
  if (isSingleEmoji(q)) return [q];
  const terms = q.split(/\s+/u);
  const seen = new Set<string>();
  const out: string[] = [];
  for (const [emoji, words] of CATALOGUE) {
    if (seen.has(emoji)) continue;
    const list = words.split(' ');
    if (terms.every((term) => list.some((word) => word.startsWith(term)))) {
      seen.add(emoji);
      out.push(emoji);
    }
  }
  return out;
}

/** Every catalogue entry is one emoji (the test checks it). */
export function catalogueEmoji(): string[] {
  return CATALOGUE.map(([emoji]) => emoji);
}
