/**
 * English names of every accepted currency, singular, sentence case ("Canadian dollar"), generated from CLDR (Node's
 * ICU) for the codes in core's `CURRENCY_EXPONENTS`. Hermes on iOS has no currency display names, so `currencyName`
 * falls back to this table when `Intl` cannot name a currency.
 */
export const CURRENCY_NAMES_EN: Readonly<Record<string, string>> = Object.freeze({
  AED: 'UAE dirham',
  AFN: 'Afghan Afghani',
  ALL: 'Albanian lek',
  AMD: 'Armenian dram',
  ANG: 'Netherlands Antillean guilder',
  AOA: 'Angolan kwanza',
  ARS: 'Argentine peso',
  AUD: 'Australian dollar',
  AWG: 'Aruban florin',
  AZN: 'Azerbaijani manat',
  BAM: 'Bosnia-Herzegovina convertible mark',
  BBD: 'Barbadian dollar',
  BDT: 'Bangladeshi taka',
  BGN: 'Bulgarian lev',
  BHD: 'Bahraini dinar',
  BIF: 'Burundian franc',
  BMD: 'Bermudan dollar',
  BND: 'Brunei dollar',
  BOB: 'Bolivian boliviano',
  BOV: 'Bolivian mvdol',
  BRL: 'Brazilian real',
  BSD: 'Bahamian dollar',
  BTN: 'Bhutanese ngultrum',
  BWP: 'Botswanan pula',
  BYN: 'Belarusian ruble',
  BZD: 'Belize dollar',
  CAD: 'Canadian dollar',
  CDF: 'Congolese franc',
  CHE: 'WIR euro',
  CHF: 'Swiss franc',
  CHW: 'WIR franc',
  CLF: 'Chilean unit of account (UF)',
  CLP: 'Chilean peso',
  CNY: 'Chinese yuan',
  COP: 'Colombian peso',
  COU: 'Colombian real value unit',
  CRC: 'Costa Rican colón',
  CUC: 'Cuban convertible peso',
  CUP: 'Cuban peso',
  CVE: 'Cape Verdean escudo',
  CZK: 'Czech koruna',
  DJF: 'Djiboutian franc',
  DKK: 'Danish krone',
  DOP: 'Dominican peso',
  DZD: 'Algerian dinar',
  EGP: 'Egyptian pound',
  ERN: 'Eritrean nakfa',
  ETB: 'Ethiopian birr',
  EUR: 'Euro',
  FJD: 'Fijian dollar',
  FKP: 'Falkland Islands pound',
  GBP: 'British pound',
  GEL: 'Georgian lari',
  GHS: 'Ghanaian cedi',
  GIP: 'Gibraltar pound',
  GMD: 'Gambian dalasi',
  GNF: 'Guinean franc',
  GTQ: 'Guatemalan quetzal',
  GYD: 'Guyanaese dollar',
  HKD: 'Hong Kong dollar',
  HNL: 'Honduran lempira',
  HTG: 'Haitian gourde',
  HUF: 'Hungarian forint',
  IDR: 'Indonesian rupiah',
  ILS: 'Israeli new shekel',
  INR: 'Indian rupee',
  IQD: 'Iraqi dinar',
  IRR: 'Iranian rial',
  ISK: 'Icelandic króna',
  JMD: 'Jamaican dollar',
  JOD: 'Jordanian dinar',
  JPY: 'Japanese yen',
  KES: 'Kenyan shilling',
  KGS: 'Kyrgyz som',
  KHR: 'Cambodian riel',
  KMF: 'Comorian franc',
  KPW: 'North Korean won',
  KRW: 'South Korean won',
  KWD: 'Kuwaiti dinar',
  KYD: 'Cayman Islands dollar',
  KZT: 'Kazakhstani tenge',
  LAK: 'Laotian kip',
  LBP: 'Lebanese pound',
  LKR: 'Sri Lankan rupee',
  LRD: 'Liberian dollar',
  LSL: 'Lesotho loti',
  LYD: 'Libyan dinar',
  MAD: 'Moroccan dirham',
  MDL: 'Moldovan leu',
  MGA: 'Malagasy ariary',
  MKD: 'Macedonian denar',
  MMK: 'Myanmar kyat',
  MNT: 'Mongolian tugrik',
  MOP: 'Macanese pataca',
  MRU: 'Mauritanian ouguiya',
  MUR: 'Mauritian rupee',
  MVR: 'Maldivian rufiyaa',
  MWK: 'Malawian kwacha',
  MXN: 'Mexican peso',
  MXV: 'Mexican investment unit',
  MYR: 'Malaysian ringgit',
  MZN: 'Mozambican metical',
  NAD: 'Namibian dollar',
  NGN: 'Nigerian naira',
  NIO: 'Nicaraguan córdoba',
  NOK: 'Norwegian krone',
  NPR: 'Nepalese rupee',
  NZD: 'New Zealand dollar',
  OMR: 'Omani rial',
  PAB: 'Panamanian balboa',
  PEN: 'Peruvian sol',
  PGK: 'Papua New Guinean kina',
  PHP: 'Philippine peso',
  PKR: 'Pakistani rupee',
  PLN: 'Polish zloty',
  PYG: 'Paraguayan guarani',
  QAR: 'Qatari riyal',
  RON: 'Romanian leu',
  RSD: 'Serbian dinar',
  RUB: 'Russian ruble',
  RWF: 'Rwandan franc',
  SAR: 'Saudi riyal',
  SBD: 'Solomon Islands dollar',
  SCR: 'Seychellois rupee',
  SDG: 'Sudanese pound',
  SEK: 'Swedish krona',
  SGD: 'Singapore dollar',
  SHP: 'St. Helena pound',
  SLE: 'Sierra Leonean leone',
  SLL: 'Sierra Leonean leone (1964—2022)',
  SOS: 'Somali shilling',
  SRD: 'Surinamese dollar',
  SSP: 'South Sudanese pound',
  STN: 'São Tomé & Príncipe dobra',
  SVC: 'Salvadoran colón',
  SYP: 'Syrian pound',
  SZL: 'Swazi lilangeni',
  THB: 'Thai baht',
  TJS: 'Tajikistani somoni',
  TMT: 'Turkmenistani manat',
  TND: 'Tunisian dinar',
  TOP: 'Tongan paʻanga',
  TRY: 'Turkish lira',
  TTD: 'Trinidad & Tobago dollar',
  TWD: 'New Taiwan dollar',
  TZS: 'Tanzanian shilling',
  UAH: 'Ukrainian hryvnia',
  UGX: 'Ugandan shilling',
  USD: 'US dollar',
  USN: 'US dollar (next day)',
  UYI: 'Uruguayan peso (indexed units)',
  UYU: 'Uruguayan peso',
  UYW: 'Uruguayan nominal wage index unit',
  UZS: 'Uzbekistani som',
  VED: 'Bolívar Soberano',
  VES: 'Venezuelan bolívar',
  VND: 'Vietnamese dong',
  VUV: 'Vanuatu vatu',
  WST: 'Samoan tala',
  XAF: 'Central African CFA franc',
  XCD: 'East Caribbean dollar',
  XCG: 'Caribbean guilder',
  XOF: 'West African CFA franc',
  XPF: 'CFP franc',
  YER: 'Yemeni rial',
  ZAR: 'South African rand',
  ZMW: 'Zambian kwacha',
  ZWG: 'Zimbabwean gold',
  ZWL: 'Zimbabwean dollar (2009–2024)',
});
