/**
 * Hrefs this stack navigates to. Typed routes are generated by Metro and are stale until it runs (and the group
 * screen belongs to another stack), so the paths are cast here, in one place.
 */
import type { Href } from 'expo-router';

export const hrefs = {
  groups: '/' as Href,
  create: '/create' as Href,
  join: '/join' as Href,
  settings: '/settings' as Href,
  about: '/about' as Href,
  diagnostics: '/diagnostics' as Href,
  group: (localId: string): Href => `/group/${encodeURIComponent(localId)}` as Href,
  joinWithCode: (code: string): Href => `/join?code=${encodeURIComponent(code)}` as Href,
  pickName: (localId: string): Href => `/join?localId=${encodeURIComponent(localId)}` as Href,
};
